---
- name: nginx installation
  hosts: [myVM]
  # hosts: myVM
  become: yes

  tasks:
    

    - name: Set nginx port using Jenkins variable
      set_fact:
        nginx_port: "{{ lookup('env', 'NGINX_PORT') | default('80') }}"

    - name: Print nginx port
      debug:
        msg: "Nginx will be configured to listen on port {{ nginx_port }}"
      
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install nginx
      apt:
        name: nginx
        state: present

    # - name: Start nginx service
    #   systemd:
    #     name: nginx
    #     state: started
    #     enabled: yes

    - name: add new index.html
      copy:
        src: "{{ playbook_dir }}/../webfile/index.html"
        dest: "/var/www/html/index.html"
    
    # - name: add new nginx.conf
    #   copy:
    #     src: "{{ playbook_dir }}/nginx.conf.j2" 
    #     dest: "/etc/nginx/sites-available/default"

    - name: Deploy nginx.conf rendered with the selected port
      template:
        src: "{{ playbook_dir }}/nginx.conf.j2"
        dest: /etc/nginx/sites-available/default
        owner: root
        group: root
        mode: '0644'
      notify: Restart nginx

    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
    # - name: Configure nginx to listen on the custom port
    #   template:
    #     src: nginx.conf
    #     dest: "/etc/nginx/sites-available/default"
    #   notify: restart nginx
  
    # - name: symlink nginx.conf
    #   file:
    #     src: /etc/nginx/sites-available/default
    #     dest: /etc/nginx/sites-enabled/default
    #     state: link
    # - name: restart nginx
 
    