---
- name: nginx installation
  hosts: myVM
  become: yes

  tasks:
   
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Start nginx service
      systemd:
        name: nginx
        state: started
        enabled: yes
    
    

    # - name: enable and start firewalld service
    #   systemd:
    #     name: firewalld
    #     state: started
    #     enabled: yes
    # - name: permit traffic in default zone on port 22/tcp
    #   ansible.posix.firewalld:
    #     port: 22/tcp
    #     permanent: yes
    #     state: enabled
    #     immediate: yes
    # - name: permit traffic in default zone on port 3306/tcp
    #   ansible.posix.firewalld:
    #     port: 3306/tcp
    #     permanent: yes
    #     state: enabled
    #     immediate: yes

 
    