- name: nginx installation
  hosts: myVM
  become: yes

  tasks:
    # - name: enable and start firewalld service
    #   systemd:
    #     name: firewalld
    #     state: started
    #     enabled: yes
    # - name: permit traffic in default zone on port 22/tcp
    #   ansible.posix.firewalld:
    #     port: 22/tcp
    #     permanent: yes
    #     state: enabled
    #     immediate: yes
    # - name: permit traffic in default zone on port 3306/tcp
    #   ansible.posix.firewalld:
    #     port: 3306/tcp
    #     permanent: yes
    #     state: enabled
    #     immediate: yes

    - name: install nginx
      ansible.builtin.yum:
        name: nginx
        state: present
    - name: start nginx
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: yes
    - name: use jenkins vault secret
      ansible.builtin.debug:
        msg: "{{ lookup('community.general.vault', 'jenkins') }}"
    